
spring:
  config:
    import: vault://
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
  boot:
    admin:
      client:
        url: http://${monitoramentoHost}:9000
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}

sistema:
  eureka:
    host: ${eurekaServerHost}
    login: ${eurekaServerUser}
    senha: ${eurekaServerPass}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${sistema.eureka.login}:${sistema.eureka.senha}@${sistema.eureka.host}:8761/eureka'
  instance:
    hostname: ${sistema.eureka.host}
