version: '3'

volumes:
  data:

services:
  postgresql:
    image: postgres
    container_name: postgres-sistema
    restart: always
    environment:
      - POSTGRES_PASSWORD=Postgres2018!
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"