version: '3'

volumes:
  data:

services:
  
  postgresql:
    image: postgres
    container_name: postgres-sistema
    restart: always
    environment:
      - POSTGRES_PASSWORD=Postgres2018!
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"

  vault:
    image: guilhermejr/vault
    container_name: vault-sistema
    restart: always
    ports:
      - 8200:8200
    volumes:
      - "./vault:/root/vault/data"
      
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - 2181:2181

  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: localhost
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181