spring:
  config:
    import: 'vault://, configserver:'
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
    config:
      discovery:
        serviceId: config-server
      username: ${CONFIG_USER:config}
      password: ${CONFIG_PASS:o5qByEjgPOwh3yXOqf}
  boot:
    admin:
      client:
        url: http://${monitoramentoHost}:9000
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}
        instance:
          metadata:
            user:
              name: ${actuatorUser}
              password: ${actuatorPass}