
spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
        username: admin
        password: 8eJeakZoGeZwp351k2
        instance:
          metadata:
            user:
              name: actuator
              password: 3xBv6lN3lPWX8jjiSa

sistema:
  eureka:
    login: eureka
    senha: mMnsilmomkq0bFiktR

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: 'http://${sistema.eureka.login}:${sistema.eureka.senha}@localhost:8761/eureka'