server:
  port: 9000

spring:
  application:
    name: monitoramento
  profiles:
    active: dev
    
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@